feat: devedition archive versions
browser-actions/setup-firefox pull request #517
Opened 2024-01-30 20:05 UTC by DanielSinclair

## Changes
- added ability to accept product versions in the `version` param for archive download URLs; this allows downloading historical devedition releases
- product name parsing if included in `version` (i.e. `devedition-80.0b1` or `firefox-80.0`)
- version parsing to ignore product name is specified

## Tests
- coverage of product-specified versions in `ArchiveDownloadURL`, including `firefox-80.0`, `devedition-80.0b1`, and `beta-80.0b1`
- coverage of product-specified versions in `DownloadURLFactory`, including `firefox-80.0`, `beta-80.0b1`, and `devedition-80.0b1`

2024-01-30 20:17 UTC, DanielSinclair commented
@ueokande Our team noticed that we were unable to install static/historical versions of `devedition` after the `latest-devedition` introduced an issue, so I've added that ability in this PR

2024-02-17 03:46 UTC, ueokande requested changes

2024-02-17 03:46 UTC, ueokande commented on .github/workflows/build.yml
> +          firefox-version: "devedition-84.b1"
The test [fails](https://github.com/browser-actions/setup-firefox/actions/runs/7716884084/job/21678745839#step:9:8).  I think it should be `devedition-84.0b1`

```suggestion
          firefox-version: "devedition-84.0b1"
```

2024-02-26 21:36 UTC, DanielSinclair commented
@ueokande Thanks! Should be fixed now

2024-02-29 09:24 UTC, ueokande approved these changes
Thanks for your contribution!

2024-02-29 09:28 UTC, merged